<?php

namespace Marketing\MarketBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductsOfCategory($cat_id, $limit = null)
    {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.category = :category')
                ->addOrderBy('c.id', 'ASC')
                ->setParameter('category', $cat_id);

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
                  ->getResult();
    }
}
